# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/SingleDGH/ComputerEngineering/VivadoProject/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc

# Block Designs: bd/image_rotation_design/image_rotation_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design || ORIG_REF_NAME==image_rotation_design} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_axi_ip_0_0/image_rotation_design_axi_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_axi_ip_0_0 || ORIG_REF_NAME==image_rotation_design_axi_ip_0_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_processing_system7_0_0/image_rotation_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_processing_system7_0_0 || ORIG_REF_NAME==image_rotation_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_xbar_0/image_rotation_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_xbar_0 || ORIG_REF_NAME==image_rotation_design_xbar_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_ps7_0_axi_periph_0/image_rotation_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==image_rotation_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_rst_ps7_0_50M_0/image_rotation_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==image_rotation_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_blk_mem_gen_0_1/image_rotation_design_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_blk_mem_gen_0_1 || ORIG_REF_NAME==image_rotation_design_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_axi_bram_ctrl_0_1/image_rotation_design_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_axi_bram_ctrl_0_1 || ORIG_REF_NAME==image_rotation_design_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_axi_fifo_mm_s_0_0/image_rotation_design_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==image_rotation_design_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_axi_dma_0_0 || ORIG_REF_NAME==image_rotation_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_auto_pc_3/image_rotation_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_auto_pc_3 || ORIG_REF_NAME==image_rotation_design_auto_pc_3} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_auto_pc_0/image_rotation_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_auto_pc_0 || ORIG_REF_NAME==image_rotation_design_auto_pc_0} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_auto_pc_1/image_rotation_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_auto_pc_1 || ORIG_REF_NAME==image_rotation_design_auto_pc_1} -quiet] -quiet

# IP: bd/image_rotation_design/ip/image_rotation_design_auto_pc_2/image_rotation_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotation_design_auto_pc_2 || ORIG_REF_NAME==image_rotation_design_auto_pc_2} -quiet] -quiet

# XDC: bd/image_rotation_design/image_rotation_design_ooc.xdc
