# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SingleDGH/ComputerEngineering/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1.xci
# IP: The module: 'image_rotator_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SingleDGH/ComputerEngineering/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotator_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/SingleDGH/ComputerEngineering/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1.xci
# IP: The module: 'image_rotator_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SingleDGH/ComputerEngineering/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotator_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
