# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0.xci
# IP: The module: 'image_rotation_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0.xci
# IP: The module: 'image_rotation_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/SingleDGH/ComputerEngineering/VivadoProject/image_rotation_project/image_rotation_project.srcs/sources_1/bd/image_rotation_design/ip/image_rotation_design_axi_dma_0_0/image_rotation_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rotation_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
