# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-Z7-20-Master.xdc

# Block Designs: bd/img_rot_design/img_rot_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design || ORIG_REF_NAME==img_rot_design} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_processing_system7_0_0/img_rot_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_processing_system7_0_0 || ORIG_REF_NAME==img_rot_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_axi_image_rotator_0_0/img_rot_design_axi_image_rotator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_axi_image_rotator_0_0 || ORIG_REF_NAME==img_rot_design_axi_image_rotator_0_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_proc_sys_reset_0_0/img_rot_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_proc_sys_reset_0_0 || ORIG_REF_NAME==img_rot_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_axi_dma_0_0/img_rot_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_axi_dma_0_0 || ORIG_REF_NAME==img_rot_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_axi_gpio_0_0/img_rot_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_axi_gpio_0_0 || ORIG_REF_NAME==img_rot_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/img_rot_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_smartconnect_0_0 || ORIG_REF_NAME==img_rot_design_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/bd_4939.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_0/bd_4939_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4939_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_2/bd_4939_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_3/bd_4939_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_4/bd_4939_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4939_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4939_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4939_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4939_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4939_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4939_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4939_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_12/bd_4939_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_13/bd_4939_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_14/bd_4939_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_15/bd_4939_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_16/bd_4939_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_17/bd_4939_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_18/bd_4939_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_19/bd_4939_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_20/bd_4939_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_21/bd_4939_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_22/bd_4939_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_23/bd_4939_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_24/bd_4939_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_25/bd_4939_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_26/bd_4939_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/img_rot_design/ip/img_rot_design_xbar_1/img_rot_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_xbar_1 || ORIG_REF_NAME==img_rot_design_xbar_1} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_ps7_0_axi_periph_0/img_rot_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==img_rot_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/img_rot_design/ip/img_rot_design_auto_pc_0/img_rot_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_rot_design_auto_pc_0 || ORIG_REF_NAME==img_rot_design_auto_pc_0} -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_processing_system7_0_0/img_rot_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_processing_system7_0_0 || ORIG_REF_NAME==img_rot_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_proc_sys_reset_0_0/img_rot_design_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_proc_sys_reset_0_0 || ORIG_REF_NAME==img_rot_design_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_proc_sys_reset_0_0/img_rot_design_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_proc_sys_reset_0_0 || ORIG_REF_NAME==img_rot_design_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_axi_dma_0_0/img_rot_design_axi_dma_0_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_axi_dma_0_0/img_rot_design_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_axi_dma_0_0 || ORIG_REF_NAME==img_rot_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_axi_dma_0_0/img_rot_design_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_axi_dma_0_0 || ORIG_REF_NAME==img_rot_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_axi_gpio_0_0/img_rot_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_axi_gpio_0_0 || ORIG_REF_NAME==img_rot_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_axi_gpio_0_0/img_rot_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_axi_gpio_0_0/img_rot_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==img_rot_design_axi_gpio_0_0 || ORIG_REF_NAME==img_rot_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4939_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4939_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_2/bd_4939_arsw_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_3/bd_4939_rsw_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_4/bd_4939_awsw_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4939_wsw_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4939_bsw_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4939_s00a2s_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4939_sarn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_12/bd_4939_srn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_16/bd_4939_s01a2s_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_17/bd_4939_sawn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_18/bd_4939_swn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_19/bd_4939_sbn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_20/bd_4939_m00s2a_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_21/bd_4939_m00arn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_22/bd_4939_m00rn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_23/bd_4939_m00awn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_24/bd_4939_m00wn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_smartconnect_0_0/bd_0/ip/ip_25/bd_4939_m00bn_0_ooc.xdc

# XDC: bd/img_rot_design/ip/img_rot_design_auto_pc_0/img_rot_design_auto_pc_0_ooc.xdc

# XDC: bd/img_rot_design/img_rot_design_ooc.xdc
