# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/SingleDGH/ComputerEngineering/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc

# Block Designs: bd/image_rotator_design/image_rotator_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design || ORIG_REF_NAME==image_rotator_design} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_processing_system7_0_0/image_rotator_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_processing_system7_0_0 || ORIG_REF_NAME==image_rotator_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_axi_image_rotator_0_0/image_rotator_design_axi_image_rotator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_axi_image_rotator_0_0 || ORIG_REF_NAME==image_rotator_design_axi_image_rotator_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_axi_dma_0_0/image_rotator_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_axi_dma_0_0 || ORIG_REF_NAME==image_rotator_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_proc_sys_reset_0_0/image_rotator_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_proc_sys_reset_0_0 || ORIG_REF_NAME==image_rotator_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_axi_gpio_0_0/image_rotator_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_axi_gpio_0_0 || ORIG_REF_NAME==image_rotator_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_xbar_1 || ORIG_REF_NAME==image_rotator_design_xbar_1} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_ps7_0_axi_periph_0/image_rotator_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==image_rotator_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/image_rotator_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_smartconnect_0_0 || ORIG_REF_NAME==image_rotator_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_xlslice_0_0/image_rotator_design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_xlslice_0_0 || ORIG_REF_NAME==image_rotator_design_xlslice_0_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_xlslice_1_0/image_rotator_design_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_xlslice_1_0 || ORIG_REF_NAME==image_rotator_design_xlslice_1_0} -quiet] -quiet

# IP: bd/image_rotator_design/ip/image_rotator_design_auto_pc_0/image_rotator_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rotator_design_auto_pc_0 || ORIG_REF_NAME==image_rotator_design_auto_pc_0} -quiet] -quiet

# XDC: bd/image_rotator_design/image_rotator_design_ooc.xdc
