# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/LENOVO/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8400-LAPTOP-DHS056N6/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.cache/wt [current_project]
set_property parent.project_path D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.1 [current_project]
set_property ip_repo_paths d:/SingleDGH/ComputerEngineering/LogicDesign/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/new/defines.v
  D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/hdl/image_rotator_design_wrapper.v
}
add_files D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/image_rotator_design.bd
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_processing_system7_0_0/image_rotator_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_dma_0_0/image_rotator_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_dma_0_0/image_rotator_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_dma_0_0/image_rotator_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_proc_sys_reset_0_0/image_rotator_design_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_proc_sys_reset_0_0/image_rotator_design_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_proc_sys_reset_0_0/image_rotator_design_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_gpio_0_0/image_rotator_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_gpio_0_0/image_rotator_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_axi_gpio_0_0/image_rotator_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_xbar_1/image_rotator_design_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e485_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e485_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e485_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e485_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e485_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e485_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e485_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e485_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e485_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e485_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e485_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e485_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e485_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e485_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e485_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e485_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_22/bd_e485_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e485_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e485_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e485_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/ip/image_rotator_design_auto_pc_0/image_rotator_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/SingleDGH/ComputerEngineering/LogicDesign/img_rot_project/img_rot_project.srcs/sources_1/bd/image_rotator_design/image_rotator_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/SingleDGH/ComputerEngineering/LogicDesign/src_templates/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc
set_property used_in_implementation false [get_files D:/SingleDGH/ComputerEngineering/LogicDesign/src_templates/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top image_rotator_design_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef image_rotator_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file image_rotator_design_wrapper_utilization_synth.rpt -pb image_rotator_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
